In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("D:\clg_project\AI-Financial-Wellness-Coach\data\processed\Master_indian_financial_transactions.csv")
df.sample(5)

,Unnamed: 0,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country
1385,1385,TXN001386,2019-03-15,09:12:20,Employer Salary Credit,NEFT Salary Credit,44565.02,INR,NEFT,Credit,Salary,Pune,Maharashtra,India
5549,5549,TXN005163,2018-06-26,12:39:43,EMI Home Loan,Net Banking EMI Home Loan,19672.61,INR,Net Banking,Debit,Bills,Jaipur,Rajasthan,India
5106,5106,TXN006980,2018-02-06,20:00:15,Reliance Fresh,POS Purchase Reliance Fresh,3963.73,INR,Credit Card,Debit,Groceries,Indore,Madhya Pradesh,India
3051,3051,TXN003052,2018-07-28,16:41:09,Tata Power,Net Banking Payment Tata Power,4162.80,INR,Net Banking,Debit,Bills,Indore,Madhya Pradesh,India
1288,1288,TXN001289,2019-02-08,07:59:45,Jio,Auto Debit Jio,206.20,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India

In [24]:
df.dtypes

transaction_id                 str
transaction_date    datetime64[us]
transaction_time               str
merchant                       str
description                    str
amount                     float64
currency                       str
payment_method                 str
transaction_type               str
category                       str
city                           str
state                          str
country                        str
day                          int32
week                        UInt32
month                        int32
weekend                      int64
merchant_freq                int64
avg_expense                float64
rolling_avg                float64
month_end                    int64
salary_week                  int64
festival_season              int64
dtype: object

In [4]:
df["transaction_date"] = pd.to_datetime(df["transaction_date"])

In [5]:
df["day"] = df["transaction_date"].dt.day
df.columns

Index(['Unnamed: 0', 'transaction_id', 'transaction_date', 'transaction_time',
       'merchant', 'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country', 'day'],
      dtype='str')

In [6]:
df["week"] = df["transaction_date"].dt.isocalendar().week

In [7]:
df["month"] = df["transaction_date"].dt.month

In [8]:
df.columns

Index(['Unnamed: 0', 'transaction_id', 'transaction_date', 'transaction_time',
       'merchant', 'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country', 'day',
       'week', 'month'],
      dtype='str')

In [9]:
df["weekend"] = df["transaction_date"].dt.weekday.isin([5,6])
df["weekend"] = df["weekend"].astype(int)

In [10]:
df["merchant_freq"] = df["merchant"].map(df["merchant"].value_counts())

In [11]:
df.head(3)

,Unnamed: 0,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country,day,week,month,weekend,merchant_freq
0,0,TXN000001,2018-01-01,09:22:10,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,4361.84,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India,1,1,1,0,693
1,1,TXN000002,2018-01-01,12:33:23,Zepto,UPI/Paytm/Zepto,1226.03,INR,UPI,Debit,Groceries,Bengaluru,Karnataka,India,1,1,1,0,138
2,2,TXN000003,2018-01-01,20:17:30,Ace Hardware India,POS Purchase Ace Hardware India,523.73,INR,Credit Card,Debit,Miscellaneous,Bengaluru,Karnataka,India,1,1,1,0,59

In [12]:
df.drop(columns="Unnamed: 0", inplace=True)

In [13]:
df["avg_expense"] = df["amount"].mean()

In [14]:
df["rolling_avg"] = df["amount"].rolling(window=3, min_periods=1).mean()

In [23]:
df.sample(7)

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,...,day,week,month,weekend,merchant_freq,avg_expense,rolling_avg,month_end,salary_week,festival_season
3213,TXN003214,2018-09-08,14:14:04,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,2382.42,INR,Auto Debit,Debit,Bills,...,8,36,9,1,693,4989.675896,1006.396667,0,0,0
2491,TXN002492,2018-04-14,21:50:56,Blinkit,Debit Card Blinkit,729.45,INR,Debit Card,Debit,Groceries,...,14,15,4,1,140,4989.675896,542.856667,0,0,0
683,TXN000684,2018-07-27,20:56:18,Zomato,POS Purchase Zomato,415.08,INR,Debit Card,Debit,Food,...,27,30,7,0,117,4989.675896,1690.180000,0,1,0
3674,TXN003675,2018-12-16,09:39:54,Airtel,UPI/Airtel,4028.97,INR,UPI,Debit,Bills,...,16,50,12,1,175,4989.675896,17890.210000,0,0,1
448,TXN000449,2018-05-21,10:59:36,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,2790.14,INR,Auto Debit,Debit,Bills,...,21,21,5,0,693,4989.675896,17756.226667,0,0,0
4924,TXN004925,2019-09-16,10:44:08,BookMyShow,UPI Payment BookMyShow,216.75,INR,UPI,Debit,Entertainment,...,16,38,9,0,104,4989.675896,403.370000,0,0,0
5741,TXN006696,2018-08-30,16:24:08,Jio,UPI/DR/198716092/Jio,11179.41,INR,UPI,Debit,Bills,...,30,35,8,0,137,4989.675896,14510.950000,0,1,0

In [16]:
df["month_end"] = df["transaction_date"].dt.is_month_end.astype(int)

In [22]:
df["salary_week"] = ((df["day"] >= 25) | (df["day"] <=2)).astype(int)

In [19]:
fest_months = [10, 11, 12]
df["festival_season"] = df["transaction_date"].dt.month.isin(fest_months).astype(int)

In [25]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country', 'day',
       'week', 'month', 'weekend', 'merchant_freq', 'avg_expense',
       'rolling_avg', 'month_end', 'salary_week', 'festival_season'],
      dtype='str')

In [26]:
df.shape

(7000, 23)

In [27]:
df.to_csv("D:\clg_project\AI-Financial-Wellness-Coach\data\processed\Master_featured_indian_financial_transactions.csv", index=False)