In [2]:
! pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/fa/9a/31f4983f191af51ab2a8f2d0c7b33dff3a84da26533f982fff02c2f9e28b/pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Obtaining dependency information for numpy>=1.26.0 from https://files.pythonhosted.org/packages/c5/31/7fc6239c12bce7e931463251cca4426c465e1876ba3cc785402ef4dd8f4e/numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata
  Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Obtaining dependency information for tzdata from https://files.pythonhosted.org/packages/e5/6d/b53b99a9f2766d095985947a5782f1702cabb129a34f7a802d7197af832f/tzdata-2026.3-py2.py3-none-any.whl.metadata
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp311-cp311-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.1/10.0 MB 1.3 MB/s eta 0:00:08
   ---------------------------------------- 0.1/10.0 MB 980.4 kB/s eta 0:00:11
    --------------------------------------- 0.2/10.0 MB 1.4 MB/s eta 0:00:07
   - -------------------------------------- 0.3/10.0 MB 1.4 MB/s eta 0:00:07
   -- ------------------------------------- 0.5/10.0 MB 1.8 MB/s eta 0:00:06
   -- ------------------------------------- 0.6/10.0 MB 1.9 MB/s eta 0:00:05
   --- ------------------------------------ 0.9/10.0 MB 2.3 MB/s eta 0:00:04
   ---- ----------------------------------- 1.2/10.0 MB 2.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.4/10.0 MB 3.0 MB/s eta 0:00:03
   ------ --------------------------------- 1.7/10.0 MB 3.2 MB/s eta 0:00:03
   ------- -------------------------------- 2.0/10.0 MB 3.4 MB/s eta 0:00:03
   --------- ------------------------------ 2.3/10.0 MB 3.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.3/10.0 MB 3.6 MB/s eta 0:00:03
   --------- ------------------------------ 2.4/10.0 MB 3.3 MB/s eta 0:00:03
   --------- ------------------------------ 2.5/10.0 MB 3.2 MB/s eta 0:00:03
   ---------- ----------------------------- 2.5/10.0 MB 3.1 MB/s eta 0:00:03
   ---------- ----------------------------- 2.7/10.0 MB 3.1 MB/s eta 0:00:03
   ----------- ---------------------------- 2.8/10.0 MB 3.1 MB/s eta 0:00:03
   ----------- ---------------------------- 2.9/10.0 MB 3.1 MB/s eta 0:00:03
   ------------ --------------------------- 3.0/10.0 MB 3.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.1/10.0 MB 3.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.2/10.0 MB 2.9 MB/s eta 0:00:03
   ------------- -------------------------- 3.3/10.0 MB 2.8 MB/s eta 0:00:03
   ------------- -------------------------- 3.4/10.0 MB 2.8 MB/s eta 0:00:03
   -------------- ------------------------- 3.6/10.0 MB 2.9 MB/s eta 0:00:03
   --------------- ------------------------ 3.9/10.0 MB 3.0 MB/s eta 0:00:03
   ---------------- ----------------------- 4.1/10.0 MB 3.0 MB/s eta 0:00:02
   ----------------- ---------------------- 4.4/10.0 MB 3.1 MB/s eta 0:00:02
   ------------------ --------------------- 4.7/10.0 MB 3.2 MB/s eta 0:00:02
   ------------------- -------------------- 5.0/10.0 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 5.3/10.0 MB 3.4 MB/s eta 0:00:02
   ---------------------- ----------------- 5.5/10.0 MB 3.4 MB/s eta 0:00:02
   ----------------------- ---------------- 5.8/10.0 MB 3.5 MB/s eta 0:00:02
   ------------------------ --------------- 6.2/10.0 MB 3.6 MB/s eta 0:00:02
   -------------------------- ------------- 6.5/10.0 MB 3.7 MB/s eta 0:00:01
   --------------------------- ------------ 6.7/10.0 MB 3.7 MB/s eta 0:00:01
   ---------------------------- ----------- 7.0/10.0 MB 3.8 MB/s eta 0:00:01
   ----------------------------- ---------- 7.3/10.0 MB 3.8 MB/s eta 0:00:01
   ------------------------------ --------- 7.6/10.0 MB 3.8 MB/s eta 0:00:01
   ------------------------------- -------- 7.8/10.0 MB 3.9 MB/s eta 0:00:01
   -------------------------------- ------- 8.2/10.0 MB 3.9 MB/s eta 0:00:01
   --------------------------------- ------ 8.4/10.0 MB 3.9 MB/s eta 0:00:01
   ---------------------------------- ----- 8.7/10.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 9.0/10.0 MB 4.0 MB/s eta 0:00:01
   ------------------------------------- -- 9.3/10.0 MB 4.1 MB/s eta 0:00:01
   -------------------------------------- - 9.6/10.0 MB 4.1 MB/s eta 0:00:01
   ---------------------------------------  9.9/10.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  10.0/10.0 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 4.1 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp311-cp311-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.6 MB 4.1 MB/s eta 0:00:04
    --------------------------------------- 0.2/12.6 MB 3.1 MB/s eta 0:00:04
   - -------------------------------------- 0.4/12.6 MB 2.8 MB/s eta 0:00:05
   - -------------------------------------- 0.4/12.6 MB 2.3 MB/s eta 0:00:06
   ----- ---------------------------------- 1.7/12.6 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.6 MB 3.6 MB/s eta 0:00:03
   -------- ------------------------------- 2.8/12.6 MB 3.7 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.6 MB 3.9 MB/s eta 0:00:03
   ---------- ----------------------------- 3.4/12.6 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.6/12.6 MB 4.0 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.6 MB 4.1 MB/s eta 0:00:03
   ------------- -------------------------- 4.2/12.6 MB 4.2 MB/s eta 0:00:03
   -------------- ------------------------- 4.4/12.6 MB 4.2 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.6 MB 4.3 MB/s eta 0:00:02
   ---------------- ----------------------- 5.0/12.6 MB 4.4 MB/s eta 0:00:02
   ---------------- ----------------------- 5.3/12.6 MB 4.4 MB/s eta 0:00:02
   ----------------- ---------------------- 5.6/12.6 MB 4.4 MB/s eta 0:00:02
   ------------------ --------------------- 5.9/12.6 MB 4.5 MB/s eta 0:00:02
   ------------------- -------------------- 6.1/12.6 MB 4.5 MB/s eta 0:00:02
   -------------------- ------------------- 6.4/12.6 MB 4.6 MB/s eta 0:00:02
   --------------------- ------------------ 6.7/12.6 MB 4.6 MB/s eta 0:00:02
   ---------------------- ----------------- 7.0/12.6 MB 4.7 MB/s eta 0:00:02
   ----------------------- ---------------- 7.3/12.6 MB 4.7 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 4.8 MB/s eta 0:00:02
   ------------------------- -------------- 7.9/12.6 MB 4.8 MB/s eta 0:00:01
   ------------------------- -------------- 8.1/12.6 MB 4.8 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.6 MB 4.8 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 8.9/12.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------- ----------- 9.1/12.6 MB 4.9 MB/s eta 0:00:01
   ----------------------------- ---------- 9.3/12.6 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 9.3/12.6 MB 4.7 MB/s eta 0:00:01
   ------------------------------ --------- 9.5/12.6 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 9.6/12.6 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 9.7/12.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.8/12.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.1/12.6 MB 4.4 MB/s eta 0:00:01
   -------------------------------- ------- 10.4/12.6 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.6/12.6 MB 4.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.9/12.6 MB 4.8 MB/s eta 0:00:01
   ----------------------------------- ---- 11.2/12.6 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.6 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 11.8/12.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 12.1/12.6 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  12.5/12.6 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.8 MB/s eta 0:00:00
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
   ---------------------------------------- 0.0/348.2 kB ? eta -:--:--
   ------------------------------ --------- 266.2/348.2 kB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 348.2/348.2 kB 5.4 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.5 tzdata-2026.3

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

In [4]:
pf_df1 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/indian_personal_transactions_1.csv")
pf_df2 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/indian_personal_transactions_synthetic_2.csv")
pf_df3 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/new_transactions_2000.csv")

In [5]:
print(f'df1 : {pf_df1.shape}')
print(f'df2 : {pf_df2.shape}')
print(f'df3 : {pf_df3.shape}')

df1 : (2000, 13)
df2 : (3000, 13)
df3 : (2000, 13)

In [6]:
print(f'df1 : {pf_df1.columns}')
print(f'df2 : {pf_df2.columns}')
print(f'df3 : {pf_df3.columns}')

df1 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')
df2 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')
df3 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')

In [7]:
df = pd.concat([pf_df1 , pf_df2 , pf_df3] , ignore_index = True)

In [8]:
df.shape

(7000, 13)

In [10]:
df.sample()

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country
3741,TXN003742,2018-12-27,08:16:15,Flipkart,UPI Payment Flipkart,288.0,INR,UPI,Debit,Shopping,Nagpur,Maharashtra,India

In [12]:
df[(df['transaction_id'] > "TXN001995") & (df['transaction_id'] < "TXN002010")]

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country
1995,TXN001996,2019-09-29,08:22:31,Municipal Water Department,Auto Debit Municipal Water Department,225.44,INR,Auto Debit,Debit,Bills,Noida,Uttar Pradesh,India
1996,TXN001997,2019-09-30,06:22:39,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,9542.50,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India
1997,TXN001998,2019-09-30,09:03:13,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,973.88,INR,Auto Debit,Debit,Bills,Lucknow,Uttar Pradesh,India
1998,TXN001999,2019-09-30,09:23:25,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,1440.81,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India
1999,TXN002000,2019-09-30,13:33:22,Chaayos,UPI Payment Chaayos,142.20,INR,UPI,Debit,Food,Bengaluru,Karnataka,India
2000,TXN002001,2018-01-01,00:09:16,Tea Stall,UPI/Tea Stall,34.47,INR,UPI,Debit,Other,Nagpur,Maharashtra,India
2001,TXN002002,2018-01-01,16:55:43,DMart,UPI/DR/880909484/DMart,1722.01,INR,UPI,Debit,Groceries,Kolkata,West Bengal,India
2002,TXN002003,2018-01-01,18:13:10,Swiggy,UPI/Paytm/Swiggy,116.00,INR,UPI,Debit,Food,Hyderabad,Telangana,India
2003,TXN002004,2018-01-02,10:10:28,BEST,Auto Debit BEST,3690.12,INR,Auto Debit,Debit,Bills,Ahmedabad,Gujarat,India
2004,TXN002005,2018-01-02,12:09:10,Tata Power,Auto Debit Tata Power,720.95,INR,Auto Debit,Debit,Bills,Delhi,Delhi,India
2005,TXN002006,2018-01-02,15:42:07,Domino's India,UPI/Paytm/Domino's India,188.77,INR,UPI,Debit,Food,Chennai,Tamil Nadu,India
2006,TXN002007,2018-01-03,10:21:27,Tailor,UPI/Tailor,381.19,INR,UPI,Debit,Other,Indore,Madhya Pradesh,India
2007,TXN002008,2018-01-03,14:23:12,Local Services,Cash Withdrawal ATM,1301.40,INR,Cash Withdrawal,Debit,Other,Lucknow,Uttar Pradesh,India
2008,TXN002009,2018-01-03,14:53:54,Misc Vendor,Cash Withdrawal ATM,554.73,INR,Cash Withdrawal,Debit,Other,Noida,Uttar Pradesh,India

In [13]:
df.category.unique()

<StringArray>
[        'Bills',     'Groceries', 'Miscellaneous',          'Rent',
          'Food', 'Entertainment',      'Shopping',          'Fuel',
  'Subscription',        'Salary',     'Insurance',         'Other',
    'Investment']
Length: 13, dtype: str

In [14]:
df.to_csv('D:\clg_project\AI-Financial-Wellness-Coach\data\processed\Master_indian_financial_transactions.csv')