In [22]:
! pip install pandas

Requirement already satisfied: pandas in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=1.26.0 in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\clg_project\ai-financial-wellness-coach\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [23]:
import pandas as pd

In [24]:
pf_df1 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/indian_personal_transactions_1.csv")
pf_df2 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/indian_personal_transactions_synthetic_2.csv")
pf_df3 = pd.read_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_datasets/new_transactions_2000.csv")

In [25]:
print(f'df1 : {pf_df1.shape}')
print(f'df2 : {pf_df2.shape}')
print(f'df3 : {pf_df3.shape}')

df1 : (2000, 13)
df2 : (3000, 13)
df3 : (2000, 13)

In [26]:
print(f'df1 : {pf_df1.columns}')
print(f'df2 : {pf_df2.columns}')
print(f'df3 : {pf_df3.columns}')

df1 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')
df2 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')
df3 : Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')

In [27]:
df = pd.concat([pf_df1 , pf_df2 , pf_df3] , ignore_index = True)

In [28]:
df.shape

(7000, 13)

In [29]:
df.sample()

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country
6170,TXN005800,2019-01-09,05:36:08,Indian Oil,POS Purchase Indian Oil,4038.61,INR,Credit Card,Debit,Fuel,Pune,Maharashtra,India

In [30]:
df[(df['transaction_id'] > "TXN001995") & (df['transaction_id'] < "TXN002010")]

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country
1995,TXN001996,2019-09-29,08:22:31,Municipal Water Department,Auto Debit Municipal Water Department,225.44,INR,Auto Debit,Debit,Bills,Noida,Uttar Pradesh,India
1996,TXN001997,2019-09-30,06:22:39,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,9542.50,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India
1997,TXN001998,2019-09-30,09:03:13,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,973.88,INR,Auto Debit,Debit,Bills,Lucknow,Uttar Pradesh,India
1998,TXN001999,2019-09-30,09:23:25,Credit Card Bill Payment,Auto Debit Credit Card Bill Payment,1440.81,INR,Auto Debit,Debit,Bills,Bengaluru,Karnataka,India
1999,TXN002000,2019-09-30,13:33:22,Chaayos,UPI Payment Chaayos,142.20,INR,UPI,Debit,Food,Bengaluru,Karnataka,India
2000,TXN002001,2018-01-01,00:09:16,Tea Stall,UPI/Tea Stall,34.47,INR,UPI,Debit,Other,Nagpur,Maharashtra,India
2001,TXN002002,2018-01-01,16:55:43,DMart,UPI/DR/880909484/DMart,1722.01,INR,UPI,Debit,Groceries,Kolkata,West Bengal,India
2002,TXN002003,2018-01-01,18:13:10,Swiggy,UPI/Paytm/Swiggy,116.00,INR,UPI,Debit,Food,Hyderabad,Telangana,India
2003,TXN002004,2018-01-02,10:10:28,BEST,Auto Debit BEST,3690.12,INR,Auto Debit,Debit,Bills,Ahmedabad,Gujarat,India
2004,TXN002005,2018-01-02,12:09:10,Tata Power,Auto Debit Tata Power,720.95,INR,Auto Debit,Debit,Bills,Delhi,Delhi,India
2005,TXN002006,2018-01-02,15:42:07,Domino's India,UPI/Paytm/Domino's India,188.77,INR,UPI,Debit,Food,Chennai,Tamil Nadu,India
2006,TXN002007,2018-01-03,10:21:27,Tailor,UPI/Tailor,381.19,INR,UPI,Debit,Other,Indore,Madhya Pradesh,India
2007,TXN002008,2018-01-03,14:23:12,Local Services,Cash Withdrawal ATM,1301.40,INR,Cash Withdrawal,Debit,Other,Lucknow,Uttar Pradesh,India
2008,TXN002009,2018-01-03,14:53:54,Misc Vendor,Cash Withdrawal ATM,554.73,INR,Cash Withdrawal,Debit,Other,Noida,Uttar Pradesh,India

In [31]:
df.category.unique()

<StringArray>
[        'Bills',     'Groceries', 'Miscellaneous',          'Rent',
          'Food', 'Entertainment',      'Shopping',          'Fuel',
  'Subscription',        'Salary',     'Insurance',         'Other',
    'Investment']
Length: 13, dtype: str

In [32]:
df.to_csv('D:\clg_project\AI-Financial-Wellness-Coach\data\processed\Master_indian_financial_transactions.csv')

In [33]:
df.merchant.unique()

<StringArray>
[  'Credit Card Bill Payment',                      'Zepto',
         'Ace Hardware India',         'House Rent Payment',
                     'Swiggy',           'McDonald's India',
                 'BookMyShow',                       'Ajio',
            'Cafe Coffee Day',                       'BEST',
                       'HPCL',                     'Airtel',
                 'Indian Oil',                    'Spotify',
                 'Bharat Gas',                     'Myntra',
                      'Nykaa',     'Employer Salary Credit',
                       'BPCL', 'Municipal Water Department',
                    'Chaayos',                    'EatClub',
                    'Blinkit',                       'BSNL',
                     'HP Gas',           'Home Depot India',
       'Local Hardware Store',             'Domino's India',
                'Burger King',                  'BigBasket',
          'Adani Electricity',               'Amazon Prime',
               'Amazon India',                     'Faasos',
                   'Flipkart',                     'Zomato',
                        'Jio',            'Barbeque Nation',
            'Starbucks India',     'Local Wine & Beer Shop',
            'Nature's Basket',                    'Netflix',
             'Reliance Fresh',                  'Jio Fiber',
           'Local Barbershop',                 'Tata Power',
              'The Beer Cafe',                'Lakme Salon',
          'Third Wave Coffee',             'Naturals Salon',
                      'DMart',                     'Social',
                     'Meesho',                 'Indane Gas',
                        'LIC',                  'HDFC Ergo',
              'ICICI Lombard',              'Bajaj Allianz',
               'Toit Brewpub',                    'Dish TV',
                  'Tata Play',          'Airtel Digital TV',
                  'Tea Stall',                     'Tailor',
             'Local Services',                'Misc Vendor',
                'Flower Shop',                    'Laundry',
              'Street Vendor',                     'Bakery',
                  'KFC India',              'Mobile Repair',
                'Local Store',           'Unknown Merchant',
                      'IRCTC',                        'Ola',
            'Disney+ Hotstar',               'Fruit Vendor',
                'Kirana Shop',              'General Store',
           'Vegetable Market',                       'Uber',
                  'PharmEasy',            'Apollo Pharmacy',
                     'Rapido',                   'Tata 1mg',
         'Income Tax Payment',                        'KFC',
        'ICICI Prudential MF',              'EMI Home Loan',
          'EMI Personal Loan',                        'ATM',
         'Street Food Vendor',            'Interest Credit',
            'Stationery Shop',            'SBI Mutual Fund',
                   'Pet Shop',            'Mutual Fund SIP',
           'HDFC Mutual Fund']
Length: 99, dtype: str

In [34]:
Forecasting = df[['transaction_date', 'amount']]
Forecasting

     transaction_date    amount
0          2018-01-01   4361.84
1          2018-01-01   1226.03
2          2018-01-01    523.73
3          2018-01-01   1290.29
4          2018-01-02  44800.94
...               ...       ...
6995       2019-11-05  46249.96
6996       2019-11-06  13526.99
6997       2019-11-08  13617.06
6998       2019-11-08  12764.93
6999       2019-11-10  34231.00

[7000 rows x 2 columns]

In [35]:
Forecasting.to_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/processed/Forecasting.csv", index=False)

In [36]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country'],
      dtype='str')

In [38]:
merchant = df[['merchant','amount', 'category']]
merchant

                      merchant    amount       category
0     Credit Card Bill Payment   4361.84          Bills
1                        Zepto   1226.03      Groceries
2           Ace Hardware India    523.73  Miscellaneous
3                        Zepto   1290.29      Groceries
4           House Rent Payment  44800.94           Rent
...                        ...       ...            ...
6995                    Myntra  46249.96       Shopping
6996                  Flipkart  13526.99       Shopping
6997                     Nykaa  13617.06       Shopping
6998              Amazon India  12764.93       Shopping
6999                     Nykaa  34231.00       Shopping

[7000 rows x 3 columns]

In [39]:
merchant.to_csv("D:/clg_project/AI-Financial-Wellness-Coach/data/processed/merchant.csv", index=False)