In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_data/Customer_financial_profiles.csv')

In [4]:
df.head()

,id,current_age,birth_year,birth_month,gender,address,per_capita_income,yearly_income,total_debt,credit_score,...,transaction_id,date,client_id,card_id,amount,use_chip,merchant_id,merchant_city,merchant_state,zip
0,1,64,1961,3,Female,"Street 286, Indore, Madhya Pradesh - 452645",86125,1033501,280435,715,...,1251,2024-03-28,CLTIND00104,CRD001042,1483.94,Yes,MCH00496,Mumbai,Maharashtra,452645
1,2,39,1986,12,Female,"Street 268, Kolkata, West Bengal - 700555",68414,820965,0,834,...,9976,2025-09-20,CLTIND00213,CRD002132,1274.72,Yes,MCH00374,Mumbai,Maharashtra,700555
2,3,50,1975,7,Female,"Street 262, Lucknow, Uttar Pradesh - 226797",22595,271138,0,609,...,6084,2024-10-02,CLTIND03292,CRD032922,7622.04,No,MCH00108,Kolkata,West Bengal,226797
3,4,27,1998,2,Male,"Street 265, Nagpur, Maharashtra - 440623",24158,289898,0,782,...,3350,2023-09-02,CLTIND05205,CRD052053,3970.48,Yes,MCH00001,Indore,Madhya Pradesh,440623
4,5,45,1980,7,Other,"Street 157, Delhi, Delhi - 110965",45475,545697,117821,608,...,11725,2025-05-25,CLTIND04910,CRD049101,418.45,No,MCH00254,Bengaluru,Karnataka,110965

In [5]:
df.shape

(20000, 21)

In [6]:
df.columns

Index(['id', 'current_age', 'birth_year', 'birth_month', 'gender', 'address',
       'per_capita_income', 'yearly_income', 'total_debt', 'credit_score',
       'num_credit_cards', 'transaction_id', 'date', 'client_id', 'card_id',
       'amount', 'use_chip', 'merchant_id', 'merchant_city', 'merchant_state',
       'zip'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 20000 non-null  int64
 1   current_age        20000 non-null  int64
 2   birth_year         20000 non-null  int64
 3   birth_month        20000 non-null  int64
 4   gender             20000 non-null  object
 5   address            20000 non-null  object
 6   per_capita_income  20000 non-null  int64
 7   yearly_income      20000 non-null  int64
 8   total_debt         20000 non-null  int64
 9   credit_score       20000 non-null  int64
 10  num_credit_cards   20000 non-null  int64
 11  transaction_id     20000 non-null  int64
 12  date               20000 non-null  object
 13  client_id          20000 non-null  object
 14  card_id            20000 non-null  object
 15  amount             20000 non-null  float64
 16  use_chip           20000 non-null  object
 17  merchant_id        20000 non-null  object
 18  merchant_city      20000 non-null  object
 19  merchant_state     20000 non-null  object
 20  zip                20000 non-null  int64
dtypes: float64(1), int64(11), object(9)
memory usage: 3.2+ MB

In [8]:
df.describe()

,id,current_age,birth_year,birth_month,per_capita_income,yearly_income,total_debt,credit_score,num_credit_cards,transaction_id,amount,zip
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,2.000000e+04,2.000000e+04,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,10000.500000,44.210100,1980.789900,6.479150,61234.419700,7.348131e+05,1.345380e+05,702.979750,2.873750,10015.488700,3082.286901,445976.994400
std,5773.647028,14.992515,14.992515,3.459532,35354.273099,4.242512e+05,1.739757e+05,76.993944,1.162574,5802.389323,2117.081361,168230.579911
min,1.000000,19.000000,1955.000000,1.000000,12500.000000,1.500000e+05,0.000000e+00,421.000000,1.000000,1.000000,105.160000,110102.000000
25%,5000.750000,31.000000,1968.000000,3.000000,35671.000000,4.280470e+05,0.000000e+00,648.000000,2.000000,4971.000000,1531.182500,380703.500000
50%,10000.500000,44.000000,1981.000000,7.000000,54896.000000,6.587560e+05,8.250300e+04,699.000000,3.000000,10026.500000,2601.650000,440388.000000
75%,15000.250000,57.000000,1994.000000,10.000000,74842.000000,8.981090e+05,2.008720e+05,757.000000,4.000000,15062.750000,4116.155000,560252.000000
max,20000.000000,70.000000,2006.000000,12.000000,250000.000000,3.000000e+06,1.817384e+06,900.000000,5.000000,20000.000000,19806.630000,800988.000000

In [9]:
df.describe(include="object")

,gender,address,date,client_id,card_id,use_chip,merchant_id,merchant_city,merchant_state
count,20000,20000,20000,20000,20000,20000,20000,20000,20000
unique,3,4938,1035,4941,10030,2,500,15,11
top,Male,"Street 11, Lucknow, Uttar Pradesh - 226280",2024-01-22,CLTIND00062,CRD029871,Yes,MCH00471,Surat,Maharashtra
freq,9855,22,34,22,7,13927,63,1761,4132

In [10]:
df.isnull().sum()

id                   0
current_age          0
birth_year           0
birth_month          0
gender               0
address              0
per_capita_income    0
yearly_income        0
total_debt           0
credit_score         0
num_credit_cards     0
transaction_id       0
date                 0
client_id            0
card_id              0
amount               0
use_chip             0
merchant_id          0
merchant_city        0
merchant_state       0
zip                  0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)