In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/raw/main_data/mcc_codes.csv')

In [4]:
df.head()

,mcc,edited_description,combined_description,usda_description,irs_description,irs_reportable
0,742,Veterinary Services,Veterinary Services,Veterinary Services,Veterinary Services,Yes
1,763,Agricultural Co-operatives,Agricultural Co-operatives,Agricultural Co-operatives,Agricultural Cooperative,Yes
2,780,"Horticultural Services, Landscaping Services","Horticultural Services, Landscaping Services",Horticultural Services,Landscaping Services,Yes
3,1520,General Contractors-Residential and Commercial,General Contractors-Residential and Commercial,General Contractors-Residential and Commercial,General Contractors,Yes
4,1711,Air Conditioning Contractors – Sales and Insta...,Air Conditioning Contractors – Sales and Insta...,Air Conditioning Contractors – Sales and Insta...,"Heating, Plumbing, A/C",Yes

In [6]:
df.shape

(981, 6)

In [7]:
df.columns

Index(['mcc', 'edited_description', 'combined_description', 'usda_description',
       'irs_description', 'irs_reportable'],
      dtype='str')

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 981 entries, 0 to 980
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   mcc                   981 non-null    int64
 1   edited_description    981 non-null    str
 2   combined_description  973 non-null    str
 3   usda_description      706 non-null    str
 4   irs_description       963 non-null    str
 5   irs_reportable        963 non-null    str
dtypes: int64(1), str(5)
memory usage: 46.1 KB

In [9]:
df.describe()

               mcc
count   981.000000
mean   4265.234455
std    1616.143351
min     742.000000
25%    3231.000000
50%    3586.000000
75%    5094.000000
max    9950.000000

In [10]:
df.describe(include="object")

C:\Users\hp\AppData\Local\Temp\ipykernel_7548\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,edited_description,combined_description,usda_description,irs_description,irs_reportable
count,981,973,706,963,963
unique,722,714,705,285,5
top,Airlines,Airlines,Financial Institutions – Manual Cash Disbursem...,Airlines,Yes
freq,128,128,2,300,810

In [11]:
df.isnull().sum()

mcc                       0
edited_description        0
combined_description      8
usda_description        275
irs_description          18
irs_reportable           18
dtype: int64

In [12]:
df.duplicated().sum()

np.int64(0)