In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl.metadata (19 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\clg_project\ai-financial-wellness-coach\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\clg_project\ai-financial-wellness-coach\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.5-cp314-cp314-win_amd64.whl (10.0 MB)
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/10.0 MB ? eta -:--:--
   - -------------------------------------- 0.3/10.0 MB ? eta -:--:--
   -- ------------------------------------- 0.5/10.0 MB 1.6 MB/s eta 0:00:06
   --- ------------------------------------ 0.8/10.0 MB 1.6 MB/s eta 0:00:06
   ---- ----------------------------------- 1.0/10.0 MB 1.2 MB/s eta 0:00:08
   ----- ---------------------------------- 1.3/10.0 MB 1.3 MB/s eta 0:00:07
   ------ --------------------------------- 1.6/10.0 MB 1.2 MB/s eta 0:00:08
   ------- -------------------------------- 1.8/10.0 MB 1.2 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/10.0 MB 1.2 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/10.0 MB 1.2 MB/s eta 0:00:07
   ---------- ----------------------------- 2.6/10.0 MB 1.2 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/10.0 MB 1.3 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/10.0 MB 1.3 MB/s eta 0:00:06
   -------------- ------------------------- 3.7/10.0 MB 1.3 MB/s eta 0:00:05
   ---------------- ----------------------- 4.2/10.0 MB 1.4 MB/s eta 0:00:05
   ------------------ --------------------- 4.7/10.0 MB 1.5 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/10.0 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 5.5/10.0 MB 1.6 MB/s eta 0:00:03
   ------------------------- -------------- 6.3/10.0 MB 1.7 MB/s eta 0:00:03
   ---------------------------- ----------- 7.1/10.0 MB 1.8 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/10.0 MB 1.9 MB/s eta 0:00:01
   ------------------------------------- -- 9.4/10.0 MB 2.1 MB/s eta 0:00:01
   ---------------------------------------- 10.0/10.0 MB 2.2 MB/s  0:00:04
Downloading numpy-2.5.1-cp314-cp314-win_amd64.whl (12.6 MB)
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.6 MB 5.1 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.6 MB 5.3 MB/s eta 0:00:02
   ---------- ----------------------------- 3.4/12.6 MB 5.4 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 5.0 MB/s eta 0:00:02
   -------------- ------------------------- 4.5/12.6 MB 4.8 MB/s eta 0:00:02
   ----------------- ---------------------- 5.5/12.6 MB 4.5 MB/s eta 0:00:02
   ------------------- -------------------- 6.0/12.6 MB 4.4 MB/s eta 0:00:02
   ---------------------- ----------------- 7.1/12.6 MB 4.3 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.6 MB 4.5 MB/s eta 0:00:01
   ----------------------------- ---------- 9.2/12.6 MB 4.5 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.6 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.6 MB 4.4 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.6 MB 4.2 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 4.2 MB/s  0:00:02
Downloading tzdata-2026.3-py2.py3-none-any.whl (348 kB)
Installing collected packages: tzdata, numpy, pandas

   ---------------------------------------- 0/3 [tzdata]
   ---------------------------------------- 0/3 [tzdata]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   ------------- -------------------------- 1/3 [numpy]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   -------------------------- ------------- 2/3 [pandas]
   ---------------------------------------- 3/3 [pandas]

Successfully installed numpy-2.5.1 pandas-3.0.5 tzdata-2026.3

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

In [11]:
df = pd.read_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/raw/raw/Personal_Finance_Dataset.csv')

In [16]:
df.shape

(1500, 5)

In [24]:
df.columns

Index(['Date', 'Transaction Description', 'Category', 'Amount', 'Type'], dtype='str')

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     1500 non-null   str
 1   Transaction Description  1500 non-null   str
 2   Category                 1500 non-null   str
 3   Amount                   1500 non-null   float64
 4   Type                     1500 non-null   str
dtypes: float64(1), str(4)
memory usage: 58.7 KB

In [15]:
df.describe

<bound method NDFrame.describe of             Date                   Transaction Description       Category  \
0     2020-01-02                               Score each.   Food & Drink
1     2020-01-02                       Quality throughout.      Utilities
2     2020-01-04        Instead ahead despite measure ago.           Rent
3     2020-01-05  Information last everything thank serve.     Investment
4     2020-01-13              Future choice whatever from.   Food & Drink
...          ...                                       ...            ...
1495  2024-12-28                            Quite as when.           Rent
1496  2024-12-28                   Right analysis mention.  Entertainment
1497  2024-12-28                    No couple debate must.     Investment
1498  2024-12-29                  Discussion black follow.       Shopping
1499  2024-12-29         Pressure activity defense detail.          Other

       Amount     Type
0     1485.69  Expense
1     1475.58  Expense
2     1185.08  Expense
3     2291.00   Income
4     1126.88  Expense
...       ...      ...
1495   514.09  Expense
1496   727.25  Expense
1497  1425.00   Income
1498   655.78  Expense
1499  1480.00   Income

[1500 rows x 5 columns]>

In [34]:
df.head(10)

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
1,2020-01-02,Quality throughout.,Utilities,1475.58,Expense
2,2020-01-04,Instead ahead despite measure ago.,Rent,1185.08,Expense
3,2020-01-05,Information last everything thank serve.,Investment,2291.00,Income
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense
5,2020-01-14,Benefit suggest page southern.,Shopping,448.68,Expense
6,2020-01-18,By two bad fall pick.,Food & Drink,1520.03,Expense
7,2020-01-19,Court attorney product significant world.,Other,3287.00,Income
8,2020-01-21,Herself law.,Entertainment,1914.85,Expense
9,2020-01-25,Have decide environment.,Rent,766.06,Expense

In [21]:
df.isna().sum()

Date                       0
Transaction Description    0
Category                   0
Amount                     0
Type                       0
dtype: int64

In [28]:
df['Date']=pd.to_datetime(df['Date'])

In [30]:
df['Category'].unique()

<StringArray>
[    'Food & Drink',        'Utilities',             'Rent',
       'Investment',         'Shopping',            'Other',
    'Entertainment', 'Health & Fitness',           'Salary',
           'Travel']
Length: 10, dtype: str

In [32]:
df[df['Category'] == "Food & Drink"]

,Date,Transaction Description,Category,Amount,Type
0,2020-01-02,Score each.,Food & Drink,1485.69,Expense
4,2020-01-13,Future choice whatever from.,Food & Drink,1126.88,Expense
6,2020-01-18,By two bad fall pick.,Food & Drink,1520.03,Expense
14,2020-01-31,How trip learn enter.,Food & Drink,1325.91,Expense
23,2020-02-08,Around there water.,Food & Drink,465.81,Expense
...,...,...,...,...,...
1429,2024-10-07,Hundred step according.,Food & Drink,802.82,Expense
1430,2024-10-08,Group never.,Food & Drink,438.78,Expense
1451,2024-11-03,Doctor population grow bar.,Food & Drink,62.47,Expense
1467,2024-11-18,Board notice later thus.,Food & Drink,1378.66,Expense
1491,2024-12-19,Democratic recent student specific political.,Food & Drink,406.37,Expense