In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/master/Master_featured_indian_financial_transactions.csv')

In [3]:
df.sample(5)

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,...,day,week,month,weekend,merchant_freq,avg_expense,rolling_avg,month_end,salary_week,festival_season
3238,TXN003239,2018-09-12,20:14:38,Indian Oil,UPI/Indian Oil,3850.66,INR,UPI,Debit,Fuel,...,12,37,9,0,162,4989.675896,2003.580000,0,0,0
5274,TXN006083,2018-03-30,15:55:13,Local Barbershop,UPI/Paytm/Local Barbershop,210.91,INR,UPI,Debit,Miscellaneous,...,30,13,3,0,20,4989.675896,1994.246667,0,1,0
631,TXN000632,2018-07-11,09:51:48,Burger King,Debit Card POS Burger King,217.72,INR,Debit Card,Debit,Food,...,11,28,7,0,92,4989.675896,1723.833333,0,0,0
6636,TXN006758,2019-06-14,07:06:45,Amazon India,POS Purchase Amazon India,3832.49,INR,Credit Card,Debit,Shopping,...,14,24,6,0,123,4989.675896,2768.703333,0,0,0
2924,TXN002925,2018-07-02,05:09:22,ICICI Lombard,Net Banking Payment ICICI Lombard Insurance Pr...,8656.61,INR,Net Banking,Debit,Insurance,...,2,27,7,0,39,4989.675896,3063.693333,0,1,0

In [4]:
df.isnull().sum()

transaction_id      0
transaction_date    0
transaction_time    0
merchant            0
description         0
amount              0
currency            0
payment_method      0
transaction_type    0
category            0
city                0
state               0
country             0
day                 0
week                0
month               0
weekend             0
merchant_freq       0
avg_expense         0
rolling_avg         0
month_end           0
salary_week         0
festival_season     0
dtype: int64

In [5]:
df.dtypes

transaction_id          str
transaction_date        str
transaction_time        str
merchant                str
description             str
amount              float64
currency                str
payment_method          str
transaction_type        str
category                str
city                    str
state                   str
country                 str
day                   int64
week                  int64
month                 int64
weekend               int64
merchant_freq         int64
avg_expense         float64
rolling_avg         float64
month_end             int64
salary_week           int64
festival_season       int64
dtype: object

In [6]:
# checking if all ids are unique
df["transaction_id"].is_unique

True

In [7]:
#checking for entire duplicate records  
df.duplicated().sum()

np.int64(0)

In [8]:
#checking for data subset of duplicate records
df.duplicated(
    subset=[
        "transaction_date",
        "transaction_time",
        "merchant",
        "amount",
        "description"
    ]
).sum()

np.int64(0)

In [9]:
#changing datatype of date column
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"]
)

In [10]:
df.dtypes

transaction_id                 str
transaction_date    datetime64[us]
transaction_time               str
merchant                       str
description                    str
amount                     float64
currency                       str
payment_method                 str
transaction_type               str
category                       str
city                           str
state                          str
country                        str
day                          int64
week                         int64
month                        int64
weekend                      int64
merchant_freq                int64
avg_expense                float64
rolling_avg                float64
month_end                    int64
salary_week                  int64
festival_season              int64
dtype: object

In [11]:
print(df["transaction_date"].min())
print(df["transaction_date"].max())

2018-01-01 00:00:00
2019-11-10 00:00:00

In [12]:
df['amount'].describe()

count      7000.000000
mean       4989.675896
std       13768.784894
min          30.740000
25%         489.030000
50%        1382.480000
75%        3620.717500
max      240125.840000
Name: amount, dtype: float64

In [13]:
#checking if there are some zero amount records
print("Zero:", (df["amount"] == 0).sum())
print("Negative:", (df["amount"] < 0).sum())

Zero: 0
Negative: 0

In [14]:
#currency validation
df.currency.value_counts()

currency
INR    7000
Name: count, dtype: int64

In [15]:
#country validation
df.country.value_counts()

country
India    7000
Name: count, dtype: int64

In [16]:
#Transaction Type validation

df.transaction_type.value_counts()

transaction_type
Debit     6810
Credit     190
Name: count, dtype: int64

In [17]:
df.transaction_type.unique()

<StringArray>
['Debit', 'Credit']
Length: 2, dtype: str

In [18]:
df.payment_method.value_counts()

payment_method
UPI                2607
Auto Debit         1333
Debit Card         1053
Net Banking         816
Credit Card         697
NEFT                307
Cash Withdrawal      95
IMPS                 92
Name: count, dtype: int64

In [19]:
pd.crosstab(df["merchant"], df["category"])

category,Bills,Entertainment,Food,Fuel,Groceries,Insurance,Investment,Miscellaneous,Other,Rent,Salary,Shopping,Subscription
merchant,,,,,,,,,,,,,
ATM,0,0,0,0,0,0,0,0,17,0,0,0,0
Ace Hardware India,0,0,0,0,0,0,0,59,0,0,0,0,0
Adani Electricity,98,0,0,0,0,0,0,0,0,0,0,0,0
Airtel,175,0,0,0,0,0,0,0,0,0,0,0,0
Airtel Digital TV,0,0,0,0,0,0,0,0,0,0,0,0,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uber,0,0,0,0,0,0,0,21,0,0,0,0,0
Unknown Merchant,0,0,0,0,0,0,0,0,28,0,0,0,0
Vegetable Market,0,0,0,0,0,0,0,0,27,0,0,0,0
Zepto,0,0,0,0,138,0,0,0,0,0,0,0,0
Zomato,0,0,117,0,0,0,0,0,0,0,0,0,0

In [20]:
df['category'].value_counts()

category
Bills            2059
Food             1328
Groceries         912
Shopping          550
Other             435
Fuel              423
Miscellaneous     358
Subscription      242
Salary            173
Entertainment     167
Rent              165
Insurance         152
Investment         36
Name: count, dtype: int64

In [21]:
df['merchant'].value_counts()

merchant
Credit Card Bill Payment    693
DMart                       178
Airtel                      175
Reliance Fresh              167
House Rent Payment          165
                           ...
Street Food Vendor            9
Stationery Shop               9
Pet Shop                      8
HDFC Mutual Fund              8
SBI Mutual Fund               5
Name: count, Length: 99, dtype: int64

In [22]:
print(list(df.merchant.unique()))

['Credit Card Bill Payment', 'Zepto', 'Ace Hardware India', 'House Rent Payment', 'Swiggy', "McDonald's India", 'BookMyShow', 'Ajio', 'Cafe Coffee Day', 'BEST', 'HPCL', 'Airtel', 'Indian Oil', 'Spotify', 'Bharat Gas', 'Myntra', 'Nykaa', 'Employer Salary Credit', 'BPCL', 'Municipal Water Department', 'Chaayos', 'EatClub', 'Blinkit', 'BSNL', 'HP Gas', 'Home Depot India', 'Local Hardware Store', "Domino's India", 'Burger King', 'BigBasket', 'Adani Electricity', 'Amazon Prime', 'Amazon India', 'Faasos', 'Flipkart', 'Zomato', 'Jio', 'Barbeque Nation', 'Starbucks India', 'Local Wine & Beer Shop', "Nature's Basket", 'Netflix', 'Reliance Fresh', 'Jio Fiber', 'Local Barbershop', 'Tata Power', 'The Beer Cafe', 'Lakme Salon', 'Third Wave Coffee', 'Naturals Salon', 'DMart', 'Social', 'Meesho', 'Indane Gas', 'LIC', 'HDFC Ergo', 'ICICI Lombard', 'Bajaj Allianz', 'Toit Brewpub', 'Dish TV', 'Tata Play', 'Airtel Digital TV', 'Tea Stall', 'Tailor', 'Local Services', 'Misc Vendor', 'Flower Shop', 'Laundry', 'Street Vendor', 'Bakery', 'KFC India', 'Mobile Repair', 'Local Store', 'Unknown Merchant', 'IRCTC', 'Ola', 'Disney+ Hotstar', 'Fruit Vendor', 'Kirana Shop', 'General Store', 'Vegetable Market', 'Uber', 'PharmEasy', 'Apollo Pharmacy', 'Rapido', 'Tata 1mg', 'Income Tax Payment', 'KFC', 'ICICI Prudential MF', 'EMI Home Loan', 'EMI Personal Loan', 'ATM', 'Street Food Vendor', 'Interest Credit', 'Stationery Shop', 'SBI Mutual Fund', 'Pet Shop', 'Mutual Fund SIP', 'HDFC Mutual Fund']

In [23]:
df.groupby(['category' , 'merchant'])['amount'].sum()

category      merchant
Bills         Adani Electricity    594778.24
              Airtel               619846.61
              BEST                 529828.59
              BSNL                 457372.17
              Bharat Gas           267541.77
                                     ...
Subscription  Dish TV               15277.94
              Disney+ Hotstar       10801.44
              Netflix               10707.76
              Spotify               25995.34
              Tata Play             11931.55
Name: amount, Length: 102, dtype: float64

In [24]:
merchant_category_counts = (
    df.groupby("merchant")["category"]
      .nunique()
      .sort_values(ascending=False)
)

merchant_category_counts[
    merchant_category_counts > 1
]

merchant
Amazon Prime       2
Disney+ Hotstar    2
Netflix            2
Name: category, dtype: int64

In [25]:
df[
    df["merchant"].isin(
        merchant_category_counts[
            merchant_category_counts > 1
        ].index
    )
][["merchant", "category"]].drop_duplicates()

             merchant       category
66       Amazon Prime  Entertainment
100           Netflix  Entertainment
2046     Amazon Prime   Subscription
2073          Netflix   Subscription
2187  Disney+ Hotstar   Subscription
5208  Disney+ Hotstar  Entertainment

In [26]:
#Time Validation
df.transaction_time.head()

0    09:22:10
1    12:33:23
2    20:17:30
3    21:33:19
4    08:43:33
Name: transaction_time, dtype: str

In [27]:
# Changing Time format

df["transaction_time"] = pd.to_datetime(
    df["transaction_time"],
    format="%H:%M:%S",
    errors="coerce"
).dt.time

In [28]:
df.transaction_time.head()

0    09:22:10
1    12:33:23
2    20:17:30
3    21:33:19
4    08:43:33
Name: transaction_time, dtype: object

In [29]:
df["transaction_time"].isna().sum()

np.int64(0)

In [30]:
# some rows are calculated using whole data it  might perform data leakage

In [31]:
df.drop(columns = ['merchant_freq', 'avg_expense', 'rolling_avg'] , inplace = True)

In [32]:
df.columns

Index(['transaction_id', 'transaction_date', 'transaction_time', 'merchant',
       'description', 'amount', 'currency', 'payment_method',
       'transaction_type', 'category', 'city', 'state', 'country', 'day',
       'week', 'month', 'weekend', 'month_end', 'salary_week',
       'festival_season'],
      dtype='str')

In [33]:
# Description Validation
print(df["description"].isna().sum())
print(df["description"].nunique())

0
1176

In [34]:
df['description'].value_counts().head(20)

description
Auto Debit Credit Card Bill Payment             369
Net Banking Payment Credit Card Bill Payment    273
NEFT Salary Credit                              163
Auto Debit Airtel                                85
Auto Debit Municipal Water Department            79
POS Purchase Amazon India                        70
Auto Debit Jio                                   67
Auto Debit Spotify                               60
Auto Debit Jio Fiber                             58
Auto Debit BSNL                                  57
NEFT Rent Payment                                56
UPI/Paytm/Zomato                                 55
POS Purchase Flipkart                            53
Cash Withdrawal ATM                              53
POS Purchase Myntra                              52
UPI/Paytm/Swiggy                                 50
Auto Debit BEST                                  48
Auto Debit Tata Power                            48
Auto Debit Bharat Gas                            47
Auto Debit Adani Electricity                     45
Name: count, dtype: int64

In [35]:
#amount/category relationship

df.groupby("category")["amount"].agg(
    ["count", "mean", "median", "min", "max"]
).sort_values("mean", ascending=False)

               count          mean     median      min        max
category
Salary           173  64481.613931  46862.710   114.38  240125.84
Rent             165  26602.182848  30940.780  7542.54   47664.75
Investment        36  22752.809444  20718.725  2485.40   48875.36
Insurance        152  14284.709079   8584.340  2237.12   48355.87
Bills           2059   4498.560690   2734.380   187.00   39289.29
Shopping         550   4272.011818   1317.845   288.00   49971.86
Fuel             423   2968.794468   3097.930   282.59    5000.00
Miscellaneous    358   1777.411397    875.750    60.00   14131.51
Groceries        912   1301.034156    855.480   300.00    4978.56
Other            435   1013.270575    783.330    30.74    4785.00
Food            1328    805.576498    469.685   116.00    2990.00
Entertainment    167    587.277665    325.250   149.00    1990.41
Subscription     242    385.214298    303.985   149.00     850.00

In [36]:
# checking class imbalance
category_counts = df["category"].value_counts()

category_percentage = (
    df["category"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print(category_percentage)

category
Bills            29.41
Food             18.97
Groceries        13.03
Shopping          7.86
Other             6.21
Fuel              6.04
Miscellaneous     5.11
Subscription      3.46
Salary            2.47
Entertainment     2.39
Rent              2.36
Insurance         2.17
Investment        0.51
Name: proportion, dtype: float64

In [37]:
df[[
    "transaction_date",
    "day",
    "week",
    "month",
    "weekend",
    "month_end",
    "salary_week",
    "festival_season"
]].head(20)

,transaction_date,day,week,month,weekend,month_end,salary_week,festival_season
0,2018-01-01,1,1,1,0,0,1,0
1,2018-01-01,1,1,1,0,0,1,0
2,2018-01-01,1,1,1,0,0,1,0
3,2018-01-01,1,1,1,0,0,1,0
4,2018-01-02,2,1,1,0,0,1,0
5,2018-01-02,2,1,1,0,0,1,0
6,2018-01-02,2,1,1,0,0,1,0
7,2018-01-02,2,1,1,0,0,1,0
8,2018-01-02,2,1,1,0,0,1,0
9,2018-01-02,2,1,1,0,0,1,0
10,2018-01-02,2,1,1,0,0,1,0
11,2018-01-03,3,1,1,0,0,0,0
12,2018-01-03,3,1,1,0,0,0,0
13,2018-01-04,4,1,1,0,0,0,0
14,2018-01-04,4,1,1,0,0,0,0
15,2018-01-04,4,1,1,0,0,0,0
16,2018-01-05,5,1,1,0,0,0,0
17,2018-01-05,5,1,1,0,0,0,0
18,2018-01-05,5,1,1,0,0,0,0
19,2018-01-05,5,1,1,0,0,0,0

In [38]:
df.sample(5)

,transaction_id,transaction_date,transaction_time,merchant,description,amount,currency,payment_method,transaction_type,category,city,state,country,day,week,month,weekend,month_end,salary_week,festival_season
3992,TXN003993,2019-02-24,11:09:58,Chaayos,UPI/Paytm/Chaayos,116.00,INR,UPI,Debit,Food,Ahmedabad,Gujarat,India,24,8,2,1,0,0,0
2317,TXN002318,2018-03-11,22:09:05,Local Wine & Beer Shop,UPI/Paytm/Local Wine & Beer Shop,116.00,INR,UPI,Debit,Food,Mumbai,Maharashtra,India,11,10,3,1,0,0,0
298,TXN000299,2018-04-10,19:35:45,Zepto,Debit Card POS Zepto,767.31,INR,Debit Card,Debit,Groceries,Indore,Madhya Pradesh,India,10,15,4,0,0,0,0
1078,TXN001079,2018-11-30,22:25:14,Burger King,UPI Collect Burger King,368.75,INR,UPI,Debit,Food,Indore,Madhya Pradesh,India,30,48,11,0,1,1,1
5479,TXN005955,2018-05-30,14:57:55,EMI Home Loan,Auto Debit EMI Home Loan,16160.96,INR,Auto Debit,Debit,Bills,Jaipur,Rajasthan,India,30,22,5,0,0,1,0

In [39]:
print("========== FINAL DATA VALIDATION ==========")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Unique transaction IDs:", df["transaction_id"].is_unique)

print("Negative amounts:", (df["amount"] < 0).sum())
print("Zero amounts:", (df["amount"] == 0).sum())

print("Currencies:")
print(df["currency"].value_counts())

print("Countries:")
print(df["country"].value_counts())

print("Transaction types:")
print(df["transaction_type"].value_counts())

print("Payment methods:")
print(df["payment_method"].value_counts())

print("Categories:")
print(df["category"].value_counts())

print("Date range:")
print(df["transaction_date"].min(), "→", df["transaction_date"].max())

========== FINAL DATA VALIDATION ==========
Rows: 7000
Columns: 20
Missing values: 0
Duplicate rows: 0
Unique transaction IDs: True
Negative amounts: 0
Zero amounts: 0
Currencies:
currency
INR    7000
Name: count, dtype: int64
Countries:
country
India    7000
Name: count, dtype: int64
Transaction types:
transaction_type
Debit     6810
Credit     190
Name: count, dtype: int64
Payment methods:
payment_method
UPI                2607
Auto Debit         1333
Debit Card         1053
Net Banking         816
Credit Card         697
NEFT                307
Cash Withdrawal      95
IMPS                 92
Name: count, dtype: int64
Categories:
category
Bills            2059
Food             1328
Groceries         912
Shopping          550
Other             435
Fuel              423
Miscellaneous     358
Subscription      242
Salary            173
Entertainment     167
Rent              165
Insurance         152
Investment         36
Name: count, dtype: int64
Date range:
2018-01-01 00:00:00 → 2019-11-10 00:00:00

In [40]:
df.nunique().sort_values()

currency               1
country                1
transaction_type       2
weekend                2
festival_season        2
salary_week            2
month_end              2
payment_method         8
state                 11
month                 12
category              13
city                  15
day                   31
week                  52
merchant              99
transaction_date     653
description         1176
amount              6587
transaction_time    6655
transaction_id      7000
dtype: int64

In [41]:
df.to_csv('D:/clg_project/AI-Financial-Wellness-Coach/data/master/final_master_transaction.csv', index=False)